val:
  _target_: src.datasets.MainDataset
  data_root: ${data_root}
  name: val
  inference_mode: true
  dataset_url: ${dataset_url}
  sr: 16000
  instance_transforms: ${transforms.instance_transforms.inference}
