train: # metrics that are calculated during training 
  []

inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.SISNRi
    name: SI-SNRi

  - _target_: src.metrics.SDRi
    name: SDRi

  - _target_: src.metrics.PESQ
    name: PESQ
    sample_rate: 16000

  - _target_: src.metrics.STOI
    name: STOI
    sample_rate: 16000
