train:
  get_mix:
    _target_: src.transforms.Mix
    min_snr_in_db: -5
    max_snr_in_db: 5
    shuffle_batch: true

  audio_mix:
    _target_: torch_audiomentations.PeakNormalization
    apply_to: only_too_loud_sounds
    sample_rate: 16000
    output_type: tensor
    p: 1.0

inference: null