_target_: src.model.TDANet
num_frames: 32000
mixture_dim: 512
init_mixture_dim: 128
num_speakers: 2
stem_kernel_size: 72
stem_padding: 11
decoder_kernel_size: 5
num_layers: 4
rate: 2
use_la: true
use_ga: true
num_blocks: 16
ga_nhead: 8
ga_dropout: 0.1
ga_kernel_size: 5
