_target_: src.model.TDANet
num_frames: 32000
init_mixture_dim: 128
mixture_dim: 512
num_speakers: 2
stem_kernel_size: 72
stem_padding: 11
decoder_kernel_size: 5
num_layers: 4
rate: 2
use_la: true
use_ga: false
num_blocks: 16
ga_kernel_size: 5
ga_ffn_only: false
